accessors implementation
Kalinichev-Ilya/ruby_ror_training pull request #10
Opened 2017-09-11 20:48 UTC by Kalinichev-Ilya

2017-09-15 14:11 UTC, vkurennov requested changes

2017-09-15 14:11 UTC, vkurennov commented on lesson_9/app/modules/validation.rb
> +      @validations ||= Hash.new( {} )
Просто `||= {}`

2017-09-15 14:11 UTC, vkurennov commented on lesson_9/app/modules/validation.rb
> +          if type == :presence
Вот не зря ругался рубокоп на сложность метода. Разнеси каонкретные валидации на отдельные методы, а здесь просто вызывай их динамически через send. Тогда можно будет в других модулях добавлять новые валидаторы, не переписывая основной и полуичм гибкий и расширяемый механизм.

2017-09-19 16:07 UTC, iBublik commented
Я б рекомендовал отключить Hound CI - PR засорен комментами. Или хотя бы повесить на пре-коммит хук прогон Rubocop'а, чтоб меньше комментариев от бота было

2017-09-19 16:24 UTC, iBublik requested changes

2017-09-19 16:24 UTC, iBublik commented on lesson_9/app/modules/accessors.rb
> +      name = "@#{method}".to_sym
Не обязательно к символу приводить. Почти все методы, которые принимают символ, могут и со строкой работать

2017-09-19 16:24 UTC, iBublik commented on lesson_9/app/modules/accessors.rb
> +        instance_variable_get(container_name) << var
Считыва значение через геттер. Он уже содержит логику установки дефолтного значения. Тогда можно 2 строки в одну свернуть - `send("#{method}_history") << var`

2017-09-19 16:24 UTC, iBublik commented on lesson_9/app/modules/validation.rb
> +      self.class.validations.each do |name, properties|
Тут будет ошибка, если в классе или его предках не вызывали метод `validate` - в `@validations` будет `nil`

2017-09-19 16:24 UTC, iBublik commented on lesson_9/app/modules/validation.rb
> +      validations[name] = prop
По условиям задачи:
> К любому атрибуту можно применить несколько разных валидаторов

А у тебя только последняя валидация сохраняется

2017-09-19 16:24 UTC, iBublik commented on lesson_9/app/modules/validation.rb
> +        properties.each { |type, prop| send type, name, prop }
В методы лучше само значение атрибута передавать, чтоб не вычислять его каждый раз (это избыточно)

2017-09-19 16:24 UTC, iBublik commented on lesson_9/app/modules/validation.rb
> +      validate! ? true : false
`validate!` бросает исключение, так что тут должна быть его обработка. Сейчас `false` никогда не вернется

2017-09-19 16:24 UTC, iBublik commented on lesson_9/app/modules/validation.rb
> +  def presence(*attr)
Ну все аргументы схлопывать неудобно. Можно так сделать - `def presence(attr, *)`. Тогда первый параметр можно использовать как обычно, а все остальные свернутся в массив.

2017-09-19 18:58 UTC, Kalinichev-Ilya commented on lesson_9/app/modules/accessors.rb
> +        instance_variable_get(container_name) << var
не понял

2017-09-19 19:07 UTC, Kalinichev-Ilya commented on lesson_9/app/modules/validation.rb
> +      validations[name] = prop
![51faefcc453bb25a9c8b97179ba93f11](https://user-images.githubusercontent.com/21128181/30610471-e46e3c4a-9d86-11e7-90dd-2b7c60a04e1d.png)
![e91a684163981f8c4bbc6a1636be8daf](https://user-images.githubusercontent.com/21128181/30610472-e472f488-9d86-11e7-8a3b-95fe7c9b2b1e.png)
М-м-м добавляются все)

2017-09-19 19:10 UTC, Kalinichev-Ilya commented on lesson_9/app/modules/validation.rb
> +      self.class.validations.each do |name, properties|
для этого есть 
```ruby
ef inherited(sub)
      sub.validations = @validations
end
```
если в родителе есть validations то в предке тоже будет

2017-09-19 19:21 UTC, Kalinichev-Ilya commented on lesson_9/app/modules/validation.rb
> +        properties.each { |type, prop| send type, name, prop }
Прости не могу понять.. например со скрина выше
```ruby
validations = {:number=>{:format=>/^(\d{3}|[a-z]{3})-*(\d{2}|[a-z]{2})$/i, :presence=>true, :type=>String}}
name = :number
properties = {:format=>/^(\d{3}|[a-z]{3})-*(\d{2}|[a-z]{2})$/i, :presence=>true, :type=>String}
# идем по хешу properties, первая итерация
type = :format
prop = /^(\d{3}|[a-z]{3})-*(\d{2}|[a-z]{2})$/i
# делаем send, format(:number, /^(\d{3}|[a-z]{3})-*(\d{2}|[a-z]{2})$/i)
send :format, :number, /^(\d{3}|[a-z]{3})-*(\d{2}|[a-z]{2})$/i
# вызывается метод format(attr, regexp)
attr = :number
regexp = /^(\d{3}|[a-z]{3})-*(\d{2}|[a-z]{2})$/i
# ищем value
value = instance_variable_get("@#{:number}")
```
ну и сравниваем и тп
в методы значение и передаю вроде бы
аааааа все дошло
спасиб

2017-09-19 19:27 UTC, Kalinichev-Ilya commented on lesson_9/app/modules/validation.rb
> +  def presence(*attr)
вот это круто

2017-09-19 19:32 UTC, iBublik commented on lesson_9/app/modules/accessors.rb
> +        instance_variable_get(container_name) << var
Ну есть же геттер для считывания истории. Там уже присваивается пустой массив, если в переменной `nil`. Зачем это тут дублировать? Получается вместо строк
```ruby
instance_variable_set(container_name, []) unless instance_variable_defined?(container_name)
instance_variable_get(container_name) << var
```
Будет короче и понятнее
```ruby
send("#{method}_history") << var
```

2017-09-19 19:35 UTC, iBublik commented on lesson_9/app/modules/validation.rb
> +      validations[name] = prop
Вообще у нас по заданию немного другой формат валидации, но это мелочи. Допустим в базовом классе я написал `validate :number, presence: true`. В наследнике хочу еще формат проверить `validate :number, format: /\d{3}/` - это собъет проверку на presence.

2017-09-19 19:40 UTC, iBublik commented on lesson_9/app/modules/validation.rb
> +      self.class.validations.each do |name, properties|
Ну класс не должен становиться нерабочим потому что забыли какую-то строчку написать. Представь что ты библиотеку пишешь, и кто-то с ней работает как с черным ящиком. Для него ошибка будет не сильно понятна.

2017-09-20 04:30 UTC, iBublik requested changes

2017-09-20 04:30 UTC, iBublik commented on lesson_9/app/modules/validation.rb
> +    raise ArgumentError, message if attr.first || value == ''
Что за `attr.first`? У тебя не массив сюда передается

2017-09-20 04:30 UTC, iBublik commented on lesson_9/app/modules/validation.rb
> +    raise ArgumentError, message unless attr.class == class_name
Для проверки класса используй `is_a?`

2017-09-21 09:08 UTC, Kalinichev-Ilya commented on lesson_9/app/modules/validation.rb
> +      self.class.validations.each do |name, properties|
Что я тебе сделал?)) Мне приходит идея только кастомную ошибку кидать, про то что друг давай передавай парамерты в `validate` а то сранивать не чего.
Просто, как сказано в задании `validate!` запускает все проверки которые были созданы :)

2017-09-21 09:08 UTC, Kalinichev-Ilya commented on lesson_9/app/modules/validation.rb
> +    raise ArgumentError, message if attr.first || value == ''
угу да забыл исправить

2017-09-21 09:21 UTC, iBublik commented on lesson_9/app/modules/validation.rb
> +      self.class.validations.each do |name, properties|
Ну это можешь не исправлять, хотя я не вижу тут сложностей)
Либо в геттере делаешь `@validations ||= {}`, либо тут при итерации `Hash(self.class.validations).each ...`

2017-09-24 10:50 UTC, vkurennov approved these changes

2017-09-24 18:04 UTC, merged