Lesson 3
Kalinichev-Ilya/ruby_ror_training pull request #2
Opened 2017-08-09 21:13 UTC by Kalinichev-Ilya

Route, station and train entity implementation

2017-08-10 06:33 UTC, iBublik requested changes

2017-08-10 06:33 UTC, iBublik commented on lesson_3/route.rb
> +    @departure = departure
Проще хранить все станции в одном массиве. Первая элемент - начальная станция, последний - конечная. Только промежуточные станции надо будет вставлять перед последним элементом, и нельзя позволять удалить первый/последний элементы массива

2017-08-10 06:33 UTC, iBublik commented on lesson_3/route.rb
> +  def add(station)
Давай методам более понятные имена. `route.add(some_var)` - отсюда непонятно что мы добавляем маршруту. А вот `route.add_station(some_var)`  уже лучше

2017-08-10 06:33 UTC, iBublik commented on lesson_3/route.rb
> +  def stations
Если все хранить в одном массиве, до будет достаточно `attr_reader :stations`

2017-08-10 06:33 UTC, iBublik commented on lesson_3/station.rb
> +  def train_list
Просто `attr_reader :trains` выполнит ту же задачу

2017-08-10 06:33 UTC, iBublik commented on lesson_3/station.rb
> +  def trains_by_type
Сделай метод более универсальным - пусть он принимает параметр (тип поезда) и возвращает все поезда на станции с этим типом. В этом поможет метод http://devdocs.io/ruby~2.4/array#method-i-select

2017-08-10 06:33 UTC, iBublik commented on lesson_3/train.rb
> +  def accelerate(speed = 0)
В ускорение явно передается дельта (изменеие скорости), а не новое значение скорости.

2017-08-10 06:33 UTC, iBublik commented on lesson_3/train.rb
> +  def accelerate(speed = 0)
И в случае с дельтой нельзя допускать, чтоб значение скорости стало меньше 0

2017-08-10 06:33 UTC, iBublik commented on lesson_3/train.rb
> +    puts 'You need to stop the train.' unless @speed.zero?
Чтоб 2 раза проверку не делать, воспользуйся обычным условием
```ruby
if @speed.zero?
  ...
else
 ...
end
```

2017-08-10 06:33 UTC, iBublik commented on lesson_3/train.rb
> +  attr_accessor :route
Зачем объвялять аксессор, если метод `route=` ты все равно переопределил?

2017-08-10 06:33 UTC, iBublik commented on lesson_3/train.rb
> +    @station = route.stations[0]
Более правильно оперировать именно индексом станции, хранить саму станцию в инстанс переменных избыточно. По индексу мы всегда можем получить станцию из маршрута

2017-08-10 06:33 UTC, iBublik commented on lesson_3/train.rb
> +    @station = route.stations[0]
Это замечание относится ко всему классу - от `@station` надо избавляться

2017-08-10 06:33 UTC, iBublik commented on lesson_3/train.rb
> +    @station = @route.stations[@station_index + 1]
При перемещении поезда не забывай обновлять список поездов на станциях - с предыдущей станции поезд отбывает, на новую - прибывает

2017-08-10 06:33 UTC, iBublik commented on lesson_3/train.rb
> +    @station = @route.stations[@station_index + 1]
И обработай ситуацию, когда поезд на конечной станции, а мы пытаемся двигаться вперед

2017-08-10 06:33 UTC, iBublik commented on lesson_3/train.rb
> +    @station = @route.stations[@station_index - 1]
Тут тоже движение поезда, значит надо обновить список поездов на станциях
И нужно обработка случая, когда поезд на начальной станции, а мы пытаемся двинуться назад

2017-08-10 06:33 UTC, iBublik commented on lesson_3/train.rb
> +    @route.stations[@station_index - 1]
Если мы находимся на первой станции, этот метод вернет последнюю станцию маршрута (т.к. отрицательные индексы массива в Ruby берут элементы с конца)

2017-08-11 05:29 UTC, iBublik requested changes

2017-08-11 05:29 UTC, iBublik commented on lesson_3/train.rb
> +  attr_accessor :route
Зря убрал метод `route=`. В нем была важная часть логики - когда поезд устанавливают на новый маршрут, он должен становиться на начальную станцию. В общем верни его, и создай только ридер для route

2017-08-11 05:29 UTC, iBublik commented on lesson_3/train.rb
> +    if @station_index < @route.stations.count
В массиве нумерация с 0, так что тут условие неверное - мы можем уйти на 1 станцию дальше конечной
Вообще я бы создал методы-предикаты, чтоб код проще читался (`last_station?`, `first_station?`) - а то так сходу трудно воспринимаются все эти индексы

2017-08-11 05:29 UTC, iBublik commented on lesson_3/train.rb
> +      puts "We at the #{@station_index} station, have nowhere to go."
Лучше просто вывести, что мы на конечной станции - индекс пользователю ничего не даст
А вообще дальше мы будем убирать пользовательский вывод из этого класса (он ответственен только за данные, интерфейс - не его задача), так что не злоупотребляй puts'ами. Лучше просто ничего не делать или возвращать false, если операция не может быть выполнена

2017-08-11 05:29 UTC, iBublik commented on lesson_3/train.rb
> +    if @station_index + 1 > 0
Вот эту проверку я совсем не понял - в какой ситуации индекс + 1 будет меньше или равен нулю?
Вообще эта проверка избыточна. Если у нас 3 станции в маршруте и мы стоим на последней (`@station_index` равен 2), то `@route.stations[@station_index + 1]` просто вернет `nil` - вполне нормальное поведение

2017-08-11 08:09 UTC, vkurennov requested changes

2017-08-11 08:09 UTC, vkurennov commented on lesson_3/route.rb
> +    index.zero?
Что такое index и откуда он взялся в этом классе? Индекс у тебя есть у поезда, но у маршрута-то его нет. Эти методы-предикаты должны быть в классе поезда, либо принимать аргумент, как в случае с методом `last_station?`

2017-08-11 08:09 UTC, vkurennov commented on lesson_3/route.rb
> +    @stations.index(station) == @stations.count - 1
А почему бы просто не сравниnm c @stations.last? Зачем проверять по индексу?

2017-08-11 08:09 UTC, vkurennov commented on lesson_3/station.rb
> +  def initialize(name, trains = [])
Нам не нужно уметь сразу передавать массив поездов при создании станции. Поэтому инициализировать пустым массивом нужно уже внутри конструктора.

2017-08-11 08:09 UTC, vkurennov commented on lesson_3/train.rb
> +    @speed.zero? ? @wagons_count + 1 : false
У тебя здесь кол-во вагонов не изменится. Ты прибавишь к значению @wagons_count единицу, но новое значение не сохранится в переменной, т.к. нет присвоения.

проверь в irb:

```
a = 0
a + 1 #=> 1
a # чему будет равно a?
```

2017-08-11 08:09 UTC, vkurennov commented on lesson_3/train.rb
> +    last_station? ? @station_index += 1 : false
То есть, если у нас последняя станция, то мы двигаем поезду (куда, если она последняя?). А если не последняя, то возвращаем false.

2017-08-11 08:09 UTC, vkurennov commented on lesson_3/train.rb
> +    last_station? ? @route.stations[@station_index + 1] : false
Опять же - возвращаем станцию, если станция последняя? Смысл?

2017-08-11 08:09 UTC, vkurennov commented on lesson_3/train.rb
> +    @station_index < @route.stations.count - 1
У тебя содержание и название метода не совпадают. И название вводит в заблуждение. Оно читается однозначно как "последняя станция?", а при этом возвращает true, если станция не полседняя. Это запутывает и ведет к неверному пониманию кода, из-за чего выше я и оставил комментарии по этому поводу. Будт внимательно и не вводи в заблуждение тех, кто читает твой код, неверными именами.

2017-08-12 07:28 UTC, iBublik commented on lesson_3/app/route.rb
> +    @stations << last
`@stations = [first, last]` 😃

2017-08-12 07:28 UTC, iBublik commented on lesson_3/app/station.rb
> +    @trains = trains || []
Что-то я не понял в чем суть такого действия? Вряд ли кто-то явно будет передавать nil в конструктор. Так что использовать дефолтный параметр `def initialize(name, trains = [])`, и тут присваивать без всяких условий

2017-08-12 07:28 UTC, iBublik commented on lesson_3/app/train.rb
> +    if @speed + speed < 0
Можно изящно избавиться от условий - `@speed = [0, @speed + speed].max`.

2017-08-12 07:28 UTC, iBublik commented on lesson_3/app/train.rb
> +    @speed.zero? ? @wagons_count += 1 : false
Я бы написал `@wagons_count +=1 if @speed.zero?`. Такой метод вернет nil, если скорость не 0, а nil логически эквивалентен false

2017-08-12 07:28 UTC, iBublik commented on lesson_3/app/train.rb
> +    @speed.zero? ? @wagons_count += 1 : false
Это вообще ко всем подобным методам относится.

2017-08-12 07:28 UTC, iBublik commented on lesson_3/spec/route_spec.rb
> +require_relative '../app/route'
👍 за тесты

2017-08-12 07:29 UTC, iBublik commented
Все мои последние замечания носят чисто рекомендательный характер, исправлять или нет - смотри сам :)

2017-08-12 09:45 UTC, vkurennov approved these changes

2017-08-12 09:45 UTC, vkurennov commented on lesson_3/app/train.rb
> +    @wagons_count -= 1 if @speed.zero?
А если вагонов еще нет? Будет отрицательное число.

2017-08-12 10:07 UTC, merged