Lesson 4
Kalinichev-Ilya/ruby_ror_training pull request #3
Opened 2017-08-13 12:58 UTC by Kalinichev-Ilya

My decision of the fourth task

2017-08-14 06:38 UTC, iBublik requested changes

2017-08-14 06:38 UTC, iBublik commented on lesson_4/app/cargo_train.rb
> +    super(number)
Можно просто писать `super` без аргументов. В этом случае все текущие аргументы передадутся выше по цепочке наследования

2017-08-14 06:38 UTC, iBublik commented on lesson_4/app/cargo_train.rb
> +    @type = 'cargo'
Зачем нам отдельно хранить типы? Класс объекта и отражает его тип

2017-08-14 06:38 UTC, iBublik commented on lesson_4/app/route.rb
> +  def print
Можно назвать метод `to_s` - он определит то, как объект будет экранироваться. Тогда можно будет писать просо `puts station` - на экран выведется то, что вернет этот метод

2017-08-14 06:38 UTC, iBublik commented on lesson_4/app/train.rb
> +    @type = ''
Так точно делать не стоит - у объектов не может отсутствовать тип

2017-08-14 06:38 UTC, iBublik commented on lesson_4/main.rb
> +loop do
Гораздо лучше было бы сделать интерфейс в объектном стиле - создать класс Main, в конструкторе проинициализировать все необходимые данные (массивы), добавить ему один публичный метод (например `run`). Публичный метод будет выводить меню и интерпретировать ввод пользователя, а все действия будут в приватных методах

2017-08-14 06:38 UTC, iBublik commented on lesson_4/helper.rb
> +    stations.each { |station| puts "#{stations.index(station)} : #{station.name}" }
`each.with_index` - не надо в каждой итерации вручную искать станцию в списке

2017-08-14 06:38 UTC, iBublik commented on lesson_4/helper.rb
> +    stations.each { |station| puts "#{stations.index(station)} : #{station.name}" }
Это вообще ко всем переборам относится, текущее решение неэффективно

2017-08-14 06:38 UTC, iBublik commented on lesson_4/helper.rb
> +    routes.each { |route| puts "#{routes.index(route)} : \"#{route.stations[0].name} - #{route.stations[-1].name}\"" }
У тебя есть метод для экранирования маршрута, используй его

2017-08-14 06:38 UTC, iBublik commented on lesson_4/helper.rb
> +    route_index = gets.chomp.to_i
Зачем это записывать в переменную? Можно просто сразу сделать `gets.to_i` - это значение и вернет метод

2017-08-14 06:38 UTC, iBublik commented on lesson_4/helper.rb
> +    routes.each { |route| puts "#{routes.index(route)} : \"#{route.stations[0].name} - #{route.stations[-1].name}\"" }
У тебя же есть метод для вывода списка маршрутов, зачем тут дублировать его логику?

2017-08-14 06:38 UTC, iBublik commented on lesson_4/helper.rb
> +  def self.choose_a_station(stations)
Методы выбора станции/маршрута/поезда очень похожи друг на друга, может стоит общее выделить в еще один метод?

2017-08-14 06:38 UTC, iBublik commented on lesson_4/main.rb
> +            name = Helper.get_station_name
Вообще я не очень понял сути выделения части методов в Helper

2017-08-15 06:08 UTC, iBublik commented on lesson_4/main.rb
> +action = Actions.new(routes, stations, trains)
Зачем в конструктор передавать эти массивы? Лучше прямо там пустые и создать.

2017-08-15 06:47 UTC, Kalinichev-Ilya commented on lesson_4/main.rb
> +action = Actions.new(routes, stations, trains)
ну да согласен, так как передавать мы туа ничего не собираемся

2017-08-15 07:52 UTC, vkurennov approved these changes

2017-08-15 07:52 UTC, vkurennov commented on lesson_4/program.rb
> +              while @stations.count < 2
Вот этот код в when тоже стоит выннести в отдельные методы, чтобы сократить весь метод run, и вложенные case также в методы

2017-08-16 19:07 UTC, merged