implementation lesson five
Kalinichev-Ilya/ruby_ror_training pull request #4
Opened 2017-08-17 20:42 UTC by Kalinichev-Ilya

2017-08-18 06:23 UTC, iBublik requested changes

2017-08-18 06:23 UTC, iBublik commented on lesson_5/app/instance_counter.rb
> +        self.class.instances = 0
Т.е. первый инстанс мы не считаем? :)
Вообще можно так записать, будет лаконично и понятно:
```ruby
self.class.instances ||= 0
self.class.instances += 1
```

2017-08-18 06:23 UTC, iBublik commented on lesson_5/app/manufacture.rb
> + attr_accessor :manufacture_name
Два пробела для отступа :)

2017-08-18 06:23 UTC, iBublik commented on lesson_5/app/station.rb
> +    @trains
И что же делает этот метод? :) Нам нужно возвращать все созданные объекты _станций_. А тут возвращается переменная `@trains`, которая нигде не заполняется :)

2017-08-18 06:23 UTC, iBublik commented on lesson_5/app/train.rb
> +  def self.find(_number)
С нижним подчеркиванием именуются переменные, которые _не используются_. Но у тебя-то она используется

2017-08-18 06:23 UTC, iBublik commented on lesson_5/app/train.rb
> +    @trains.select { |train| train[_number] }
Кажется, ты этот метод вообще не проверял :)
У тебя используется хэш для хранения. Так что метод сводится к элементарному `@trains[number]`.

2017-08-18 07:38 UTC, Kalinichev-Ilya commented on lesson_5/app/instance_counter.rb
> +        self.class.instances = 0
"а что так можно было?", тестил вроде нормально работало, но точно не скажу с какого числа начинает считать
наверное с 1, да

2017-08-18 07:40 UTC, Kalinichev-Ilya commented on lesson_5/app/station.rb
> +    @trains
Не правильно задание понял) надо исправить

2017-08-18 07:43 UTC, Kalinichev-Ilya commented on lesson_5/app/train.rb
> +    @trains.select { |train| train[_number] }
Проверял))[https://gyazo.com/1c7c493cceae6428802ba930f519ba4d](в irb все оки токи)

2017-08-19 06:30 UTC, iBublik requested changes

2017-08-19 06:30 UTC, iBublik commented on lesson_5/app/train.rb
> +  @trains = []
Вариант с хэшом как раз был более удачным. Когда нам нужен быстрый и простой доступ по ключу - хэш идеальный выбор

2017-08-19 06:30 UTC, iBublik commented on lesson_5/app/train.rb
> +    @trains.select { |train| train.number == number }
У нас по условию задачи должен возвращаться один поезд. А `select` всегда возвращает коллекцию. В общем если отбросить тот факт, что с хэшом метод сократился бы до `@trains[number]`, то тут следует использовать `find/detect` - он находит первый элемент, для которого блок вернет `true` и возвращает его.
Но ты все же верни хэш :)

2017-08-19 14:57 UTC, Kalinichev-Ilya commented on lesson_5/app/train.rb
> +    @trains.select { |train| train.number == number }
ладноо я понял :)

2017-08-20 10:17 UTC, vkurennov approved these changes

2017-08-20 12:12 UTC, merged