lesson 7 implementation
Kalinichev-Ilya/ruby_ror_training pull request #6
Opened 2017-08-27 20:07 UTC by Kalinichev-Ilya

2017-08-28 06:03 UTC, iBublik requested changes

2017-08-28 06:03 UTC, iBublik commented on lesson_7/app/cargo_wagon.rb
> +    @occuped_place += volume if there_are_places?(volume)
Как-то громоздко отдельный метод смотрится. Можно просто так записать - `@occuped_place = [@occuped_place + volume, @capacity].min`

2017-08-28 06:03 UTC, iBublik commented on lesson_7/app/station.rb
> +  def trains_search(&block)
Зачем тут блок в прок преобразуется? Все равно ведь нигде не используется. Так делают только когда нужно пробросить блок в другой метод, но тут это не нужно

2017-08-28 06:03 UTC, iBublik commented on lesson_7/app/train.rb
> +  def wagons_search(&block)
Тут тоже бессмысленное преобразование в прок

2017-08-28 06:03 UTC, iBublik commented on lesson_7/app/wagon.rb
> +    @occuped_place += 1 if there_are_places?
Я бы не стал это в базовом классе держать. Это логика чисто пассажирского вагона.
Тут можно сделать `raise NotImplementedError`, чтоб не забыть в наследниках определить метод

2017-08-28 06:03 UTC, iBublik commented on lesson_7/program.rb
> +          volume = gets.chomp.to_i
Объем может и не целым числом быть

2017-08-28 06:03 UTC, iBublik commented on lesson_7/program.rb
> +      capacity = gets.chomp.to_i
Тут тоже не обязательно целое число

2017-08-28 06:03 UTC, iBublik commented on lesson_7/app/train.rb
> +  def wagons_search(&block)
`each_wagon` явно лучше подойдет

2017-08-28 06:03 UTC, iBublik commented on lesson_7/app/station.rb
> +  def trains_search(&block)
Странно метод называется. Разве он что-то ищет? `each_train` явно лучше подойдет

2017-08-28 06:03 UTC, iBublik commented on lesson_7/program.rb
> +      number = 1
Не нужно вручную считать индекс. В Ruby есть встроенные методы для этого. 2 варианта:
1. Чуть посложнее - возвращать Enumerator из метода, когда блок не передан, чтоб можно было чейнить вызовы (пример - `each.with_index`). Тогда тут можно будет написать `train.each_wagon.with_index ...`
2. Простой - прямо в методе проходиться по списку с помощью `each.with_index` и `yield`-ить не только вагон, но и индекс.

2017-08-28 07:34 UTC, Kalinichev-Ilya commented on lesson_7/app/cargo_wagon.rb
> +    @occuped_place += volume if there_are_places?(volume)
да надо уже запомнить этот хук

2017-08-30 03:57 UTC, iBublik commented on lesson_7/app/train.rb
> +    wagons.each_with_index { |wagon| yield(wagon) }
Зачем тут `each_with_index`?

2017-08-30 03:57 UTC, iBublik commented on lesson_7/program.rb
> +    train.each_wagons.with_index(1) do |wagon, index|
`each_wagon`

2017-08-30 03:57 UTC, iBublik commented on lesson_7/program.rb
> +      capacity = gets.chomp.to_f
У пассажирских теперь может быть нецелое число мест :) Преобразуй в конструкторе в Integer

2017-08-30 07:45 UTC, vkurennov approved these changes

2017-08-30 07:58 UTC, Kalinichev-Ilya commented on lesson_7/program.rb
> +    train.each_wagons.with_index(1) do |wagon, index|
косяк)))

2017-08-30 07:59 UTC, Kalinichev-Ilya commented on lesson_7/program.rb
> +    train.each_wagons.with_index(1) do |wagon, index|
так и знал, что где нибудь забуду

2017-08-30 08:01 UTC, merged

2017-08-30 09:11 UTC, iBublik commented on lesson_7/app/cargo_wagon.rb
> +  def initialize(capacity = 0.0)
Хмм... это не превратило значение во float

2017-08-30 09:11 UTC, iBublik commented on lesson_7/program.rb
> +      capacity = gets.chomp
Теперь в конструктор передается строка. А там нет преобразования в нужный тип, так что и храниться будет строкой - классы нерабочие теперь